#!/usr/bin/env node
// ============================================================
// BUILD CONFIG.JS
// ============================================================
// Regenerates config.js from courses.json (term/course/site config —
// hand-edited) + assignments.json (scraper-owned data).
//
// config.js exists only so index.html and classroom.html can keep loading
// a single synchronous <script> global (APP_CONFIG) — it is a build
// artifact, not a source of truth. Never hand-edit it; edit courses.json
// or assignments.json and re-run this script (or scrape_assignments.py,
// which calls this automatically).
//
//   node build-config.js
// ============================================================

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, name), 'utf8'));
}

function main() {
  const courseData = readJson('courses.json');
  const assignmentData = readJson('assignments.json');

  const config = {
    title: courseData.title,
    subtitle: courseData.subtitle,
    scrapeDate: assignmentData.scrapeDate,
    firebase: courseData.firebase,
    courses: courseData.courses,
    assignments: assignmentData.assignments,
    autoCompleted: assignmentData.autoCompleted,
  };

  const out = [
    '// ============================================================',
    '// ASSIGNMENT CALENDAR — GENERATED CONFIG',
    '// ============================================================',
    '// Do not edit this file directly — it is generated by build-config.js',
    '// from courses.json (term/course/site config) and assignments.json',
    '// (scraper-owned assignment data). Edit those instead, then run:',
    '//   node build-config.js',
    '// ============================================================',
    '',
    `const APP_CONFIG = ${JSON.stringify(config, null, 2)};`,
    '',
  ].join('\n');

  fs.writeFileSync(path.join(ROOT, 'config.js'), out);
  console.log(`Wrote config.js — ${config.assignments.length} assignments, ${Object.keys(config.courses).length} courses`);
}

main();
