// ============================================================
// ASSIGNMENT CALENDAR — GENERATED CONFIG
// ============================================================
// Do not edit this file directly — it is generated by build-config.js
// from courses.json (term/course/site config) and assignments.json
// (scraper-owned assignment data). Edit those instead, then run:
//   node build-config.js
// ============================================================

const APP_CONFIG = {
  "title": "Arjun's Assignment Calendar",
  "subtitle": "EECS 367 · EECS 373 · EECS 445 · CLCIV 371 — Fall 2026",
  "scrapeDate": "October 5, 2026",
  "firebase": {
    "apiKey": "AIzaSyCUzvAHBOMLRtrrl5uTIMe6f9sGkubTtWY",
    "authDomain": "arjun-calendar-6eefc.firebaseapp.com",
    "databaseURL": "https://arjun-calendar-6eefc-default-rtdb.firebaseio.com",
    "projectId": "arjun-calendar-6eefc",
    "storageBucket": "arjun-calendar-6eefc.firebasestorage.app",
    "messagingSenderId": "889449529154",
    "appId": "1:889449529154:web:30c71c415b277d31d992db"
  },
  "courses": {
    "eecs367": {
      "name": "EECS 367",
      "idPrefix": "367",
      "color": "#16a34a",
      "bg": "#dcfce7",
      "darkColor": "#4ade80",
      "darkBg": "#14532d",
      "platform": "autorob.org",
      "platformUrl": "https://autorob.org/",
      "gcalColorId": "2",
      "canvasPatterns": [
        "eecs 367",
        "rob 380"
      ],
      "canvasCourseId": null
    },
    "eecs373": {
      "name": "EECS 373",
      "idPrefix": "373",
      "color": "#e11d48",
      "bg": "#ffe4e6",
      "darkColor": "#fb7185",
      "darkBg": "#4c0519",
      "platform": "eecs373",
      "platformUrl": "https://www.eecs.umich.edu/courses/eecs373/index.html",
      "gcalColorId": "4",
      "gradescope": [
        {
          "url_id": "1342020",
          "label": "EECS 373"
        }
      ]
    },
    "eecs445": {
      "name": "EECS 445",
      "idPrefix": "445",
      "color": "#2563eb",
      "bg": "#dbeafe",
      "darkColor": "#60a5fa",
      "darkBg": "#1e3a5f",
      "platform": "gradescope",
      "platformUrl": "https://www.gradescope.com/",
      "gcalColorId": "9",
      "gradescope": [
        {
          "url_id": "1373988",
          "label": "EECS 445"
        }
      ]
    },
    "clciv371": {
      "name": "CLCIV 371",
      "idPrefix": "clciv",
      "color": "#7c3aed",
      "bg": "#ede9fe",
      "darkColor": "#a78bfa",
      "darkBg": "#2e1f5e",
      "platform": "canvas",
      "platformUrl": "https://umich.instructure.com/",
      "gcalColorId": "3",
      "canvasPatterns": [
        "clciv 371",
        "clciv371"
      ],
      "canvasCourseId": null
    }
  },
  "assignments": [
    {
      "id": "clciv-when-to-read-by",
      "name": "When to read by",
      "course": "clciv371",
      "due": "2026-09-02",
      "time": "10:39 AM",
      "type": "assignment",
      "points": "—",
      "hours": 1
    },
    {
      "id": "clciv-readings-for-section-tomorrow",
      "name": "Readings for Section Tomorrow ",
      "course": "clciv371",
      "due": "2026-09-02",
      "time": "2:19 PM",
      "type": "assignment",
      "points": "—",
      "hours": 1
    },
    {
      "id": "clciv-first-discussion-post",
      "name": "First Discussion Post ",
      "course": "clciv371",
      "due": "2026-09-06",
      "time": "1:23 PM",
      "type": "assignment",
      "points": "—",
      "hours": 1
    },
    {
      "id": "clciv-week-2-the-rise-of-the-polis",
      "name": "Week 2: The Rise of the Polis ",
      "course": "clciv371",
      "due": "2026-09-10",
      "time": "12:59 PM",
      "type": "assignment",
      "points": "100",
      "hours": 1
    },
    {
      "id": "373-hw4",
      "name": "HW 4",
      "course": "eecs373",
      "due": "2026-10-05",
      "time": "11:59 PM",
      "type": "homework",
      "points": "—",
      "hours": 6
    },
    {
      "id": "373-pl5",
      "name": "Lab 5 - Pre-Lab",
      "course": "eecs373",
      "due": "2026-10-06",
      "time": "6:30 PM",
      "type": "prelab",
      "points": "16",
      "hours": 1
    },
    {
      "id": "373-ideation",
      "name": "Project - Ideation Slides",
      "course": "eecs373",
      "due": "2026-10-08",
      "time": "11:59 PM",
      "type": "project",
      "points": "9",
      "hours": 8
    },
    {
      "id": "373-hw5",
      "name": "HW 5",
      "course": "eecs373",
      "due": "2026-10-12",
      "time": "11:59 PM",
      "type": "homework",
      "points": "—",
      "hours": 6
    },
    {
      "id": "373-lab5",
      "name": "Lab 5 - In-Lab",
      "course": "eecs373",
      "due": "2026-10-12",
      "time": "11:59 PM",
      "type": "lab",
      "points": "70",
      "hours": 1.5
    },
    {
      "id": "373-postlab5",
      "name": "Lab 5 - Post-Lab",
      "course": "eecs373",
      "due": "2026-10-12",
      "time": "11:59 PM",
      "type": "lab",
      "points": "14",
      "hours": 1.5
    },
    {
      "id": "445-hw2",
      "name": "Homework 2",
      "course": "eecs445",
      "due": "2026-10-16",
      "time": "4:00 PM",
      "type": "homework",
      "points": "51",
      "hours": 6
    },
    {
      "id": "367-p3-checkpoint",
      "name": "Project 3 Checkpoint - Zero Configuration FK",
      "course": "eecs367",
      "due": "2026-10-12",
      "type": "project",
      "points": "—",
      "hours": 4
    },
    {
      "id": "367-p3",
      "name": "Project 3 Final - Forward Kinematics",
      "course": "eecs367",
      "due": "2026-10-20",
      "type": "project",
      "points": "—",
      "hours": 8
    },
    {
      "id": "367-midterm",
      "name": "Midterm Exam",
      "course": "eecs367",
      "due": "2026-10-26",
      "type": "exam",
      "points": "—",
      "hours": 12
    },
    {
      "id": "clciv-exam1",
      "name": "Hour Exam 1",
      "course": "clciv371",
      "due": "2026-10-08",
      "time": "12:00 PM",
      "type": "exam",
      "points": "—",
      "hours": 12
    },
    {
      "id": "clciv-festivals-quiz",
      "name": "Festivals Quiz",
      "course": "clciv371",
      "due": "2026-10-15",
      "type": "quiz",
      "points": "—",
      "hours": 1.5
    },
    {
      "id": "clciv-exam2",
      "name": "Hour Exam 2",
      "course": "clciv371",
      "due": "2026-11-12",
      "type": "exam",
      "points": "—",
      "hours": 12
    },
    {
      "id": "clciv-final",
      "name": "Final Take-Home Exam",
      "course": "clciv371",
      "due": "2026-12-16",
      "time": "8:00 AM",
      "type": "exam",
      "points": "—",
      "hours": 12
    }
  ],
  "autoCompleted": []
};
