#!/usr/bin/env node
// ============================================================
// ASSIGNMENT CALENDAR — assignments.json Validator & Fixer
// ============================================================
// Validates assignments.json against the courses/term defined in
// courses.json — so a term rollover only requires editing courses.json;
// there's nothing left here to drift out of sync.
//
// Run:  node validate-config.js           → report only
//       node validate-config.js --fix     → auto-fix and write
//       node validate-config.js --dry-run → show fixes without writing
// ============================================================

const fs = require('fs');
const path = require('path');

const COURSES_PATH = path.join(__dirname, 'courses.json');
const ASSIGNMENTS_PATH = path.join(__dirname, 'assignments.json');
const BACKUP_DIR = path.join(__dirname, 'backups');

const VALID_TYPES = [
  'project', 'quiz', 'exam', 'homework', 'prelab',
  'ep', 'lab', 'casestudy', 'lecture', 'assignment'
];

// Words/phrases that indicate announcements or non-assignment items
const JUNK_KEYWORDS = [
  'welcome to',
  'lectures cancelled',
  'office hours',
  'exam conflict form',
  'reiterating expectations',
  'bring resume',
  'on zoom',
  'syllabus agreement form',
  'report outline assignment posted',
  'dr. brehob',
  'sections cancelled',
  'no lecture',
  'class cancelled',
  'reminder:',
  'announcement:',
  'important:',
  'note:',
  'fyi:',
  'update:',
];

// ---- Load ----
function loadCourses() {
  try {
    return JSON.parse(fs.readFileSync(COURSES_PATH, 'utf8'));
  } catch (e) {
    console.error('\x1b[31m✗ SYNTAX ERROR in courses.json:\x1b[0m', e.message);
    process.exit(1);
  }
}

function loadAssignments() {
  try {
    return JSON.parse(fs.readFileSync(ASSIGNMENTS_PATH, 'utf8'));
  } catch (e) {
    console.error('\x1b[31m✗ SYNTAX ERROR in assignments.json:\x1b[0m', e.message);
    process.exit(1);
  }
}

// ---- Validation checks ----
function validate(courseData, data) {
  const issues = [];
  const assignments = data.assignments || [];
  const autoCompleted = data.autoCompleted || [];
  const validCourses = Object.keys(courseData.courses || {});
  const idPrefixes = {};
  for (const [key, c] of Object.entries(courseData.courses || {})) {
    idPrefixes[key] = c.idPrefix;
  }

  // Track IDs for duplicate detection
  const seenIds = new Map(); // id → index
  const seenNames = new Map(); // "course::lowercase-name" → id

  assignments.forEach((a, i) => {
    const loc = `assignments[${i}] (id: "${a.id}")`;

    // 1. Required fields
    if (!a.id) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing id` });
    if (!a.name) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing name` });
    if (!a.course) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing course` });
    if (!a.due) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing due date` });
    if (!a.type) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing type` });

    // 2. Valid course
    if (a.course && !validCourses.includes(a.course)) {
      issues.push({ severity: 'error', idx: i, msg: `${loc}: unknown course "${a.course}" — not in courses.json` });
    }

    // 3. Valid type
    if (a.type && !VALID_TYPES.includes(a.type)) {
      issues.push({ severity: 'warn', idx: i, msg: `${loc}: unusual type "${a.type}"` });
    }

    // 4. ID prefix matches course
    if (a.id && a.course && idPrefixes[a.course]) {
      const prefix = a.id.split('-')[0];
      if (prefix !== idPrefixes[a.course]) {
        issues.push({ severity: 'warn', idx: i, msg: `${loc}: id prefix "${prefix}" doesn't match course "${a.course}" (expected "${idPrefixes[a.course]}")` });
      }
    }

    // 5. Long auto-generated IDs (scraper artifact)
    if (a.id && a.id.length > 25) {
      issues.push({ severity: 'warn', idx: i, msg: `${loc}: suspiciously long id (${a.id.length} chars) — likely auto-generated by scraper`, fixable: 'long-id' });
    }

    // 6. Duplicate IDs
    if (a.id && seenIds.has(a.id)) {
      issues.push({ severity: 'error', idx: i, msg: `${loc}: DUPLICATE id — also at index ${seenIds.get(a.id)}`, fixable: 'duplicate-id' });
    } else if (a.id) {
      seenIds.set(a.id, i);
    }

    // 7. Duplicate names within same course (fuzzy)
    if (a.name && a.course) {
      const nameKey = `${a.course}::${a.name.toLowerCase().replace(/\s+/g, ' ').trim()}`;
      if (seenNames.has(nameKey)) {
        issues.push({
          severity: 'warn', idx: i,
          msg: `${loc}: possible duplicate name "${a.name}" — similar to "${seenNames.get(nameKey)}"`,
          fixable: 'duplicate-name'
        });
      } else {
        seenNames.set(nameKey, a.id);
      }
    }

    // 8. Junk/announcement detection
    if (a.name) {
      const lower = a.name.toLowerCase();
      for (const kw of JUNK_KEYWORDS) {
        if (lower.includes(kw)) {
          issues.push({
            severity: 'warn', idx: i,
            msg: `${loc}: looks like an announcement/non-assignment — contains "${kw}"`,
            fixable: 'junk'
          });
          break;
        }
      }
    }

    // 9. Date format check (should be YYYY-MM-DD)
    if (a.due && !/^\d{4}-\d{2}-\d{2}$/.test(a.due)) {
      issues.push({ severity: 'error', idx: i, msg: `${loc}: invalid date format "${a.due}" (expected YYYY-MM-DD)` });
    }

    // 10. Date sanity check (should be within the current term, from courses.json)
    if (a.due && /^\d{4}-\d{2}-\d{2}$/.test(a.due) && courseData.termStart && courseData.termEnd) {
      const d = new Date(a.due + 'T12:00:00');
      const termStart = new Date(courseData.termStart + 'T00:00:00');
      const termEnd = new Date(courseData.termEnd + 'T23:59:59');
      if (d < termStart || d > termEnd) {
        issues.push({ severity: 'warn', idx: i, msg: `${loc}: date "${a.due}" is outside the ${courseData.term || 'current'} term range (${courseData.termStart}–${courseData.termEnd})` });
      }
    }

    // 11. Missing points or hours (not critical but worth noting)
    if (!a.points && a.type !== 'lecture') {
      issues.push({ severity: 'info', idx: i, msg: `${loc}: no points value` });
    }
    if (a.hours === undefined && a.type !== 'lecture') {
      issues.push({ severity: 'info', idx: i, msg: `${loc}: no hours estimate` });
    }
  });

  // 12. Stale autoCompleted references
  const allIds = new Set(assignments.map(a => a.id));
  autoCompleted.forEach(id => {
    if (!allIds.has(id)) {
      issues.push({ severity: 'warn', idx: -1, msg: `autoCompleted: stale id "${id}" not found in assignments`, fixable: 'stale-autocomplete' });
    }
  });

  // 13. Duplicate autoCompleted entries
  const seenAC = new Set();
  autoCompleted.forEach((id, i) => {
    if (seenAC.has(id)) {
      issues.push({ severity: 'warn', idx: -1, msg: `autoCompleted[${i}]: duplicate entry "${id}"`, fixable: 'duplicate-autocomplete' });
    }
    seenAC.add(id);
  });

  return issues;
}

// ---- Auto-fix ----
function autoFix(data, issues) {
  const toRemoveIdxs = new Set();
  const staleACIds = new Set();
  let fixed = 0;

  for (const issue of issues) {
    if (issue.fixable === 'duplicate-id' && issue.idx >= 0) {
      toRemoveIdxs.add(issue.idx);
      fixed++;
    }
    if (issue.fixable === 'junk' && issue.idx >= 0) {
      toRemoveIdxs.add(issue.idx);
      fixed++;
    }
    if (issue.fixable === 'duplicate-name' && issue.idx >= 0) {
      toRemoveIdxs.add(issue.idx);
      fixed++;
    }
    if (issue.fixable === 'stale-autocomplete') {
      const match = issue.msg.match(/stale id "(.+?)"/);
      if (match) staleACIds.add(match[1]);
      fixed++;
    }
  }

  // Remove flagged assignments (in reverse order to preserve indices)
  const sortedIdxs = [...toRemoveIdxs].sort((a, b) => b - a);
  for (const idx of sortedIdxs) {
    const removed = data.assignments[idx];
    console.log(`  \x1b[33m→ Removing:\x1b[0m ${removed.id} ("${removed.name}")`);
    data.assignments.splice(idx, 1);
  }

  // Clean autoCompleted: remove stale refs and deduplicate
  const remainingIds = new Set(data.assignments.map(a => a.id));
  const beforeAC = data.autoCompleted.length;
  data.autoCompleted = [...new Set(
    data.autoCompleted.filter(id => !staleACIds.has(id) && remainingIds.has(id))
  )];
  const removedAC = beforeAC - data.autoCompleted.length;
  if (removedAC > 0) {
    console.log(`  \x1b[33m→ Removed ${removedAC} stale/duplicate autoCompleted entries\x1b[0m`);
  }

  return fixed;
}

// ---- Write assignments.json back ----
function writeAssignments(data) {
  // Create backup first
  if (!fs.existsSync(BACKUP_DIR)) fs.mkdirSync(BACKUP_DIR, { recursive: true });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const backupPath = path.join(BACKUP_DIR, `assignments-${timestamp}.json`);
  fs.copyFileSync(ASSIGNMENTS_PATH, backupPath);
  console.log(`\n  \x1b[36mBackup saved:\x1b[0m ${backupPath}`);

  fs.writeFileSync(ASSIGNMENTS_PATH, JSON.stringify(data, null, 2) + '\n');
  console.log(`  \x1b[32m✓ assignments.json updated successfully\x1b[0m`);
  console.log(`  \x1b[36m→ Run 'node build-config.js' to regenerate config.js\x1b[0m`);
}

// ---- Reporting ----
function printReport(issues) {
  const errors = issues.filter(i => i.severity === 'error');
  const warns = issues.filter(i => i.severity === 'warn');
  const infos = issues.filter(i => i.severity === 'info');

  if (issues.length === 0) {
    console.log('\n\x1b[32m✓ assignments.json is clean — no issues found!\x1b[0m\n');
    return;
  }

  console.log(`\n\x1b[1m── Validation Report ──\x1b[0m\n`);

  if (errors.length > 0) {
    console.log(`\x1b[31m✗ ${errors.length} error(s):\x1b[0m`);
    errors.forEach(i => console.log(`  \x1b[31m•\x1b[0m ${i.msg}`));
    console.log();
  }
  if (warns.length > 0) {
    console.log(`\x1b[33m⚠ ${warns.length} warning(s):\x1b[0m`);
    warns.forEach(i => console.log(`  \x1b[33m•\x1b[0m ${i.msg}`));
    console.log();
  }
  if (infos.length > 0) {
    console.log(`\x1b[36mℹ ${infos.length} info:\x1b[0m`);
    infos.forEach(i => console.log(`  \x1b[36m•\x1b[0m ${i.msg}`));
    console.log();
  }

  const fixable = issues.filter(i => i.fixable).length;
  if (fixable > 0) {
    console.log(`  ${fixable} issue(s) are auto-fixable. Run with \x1b[1m--fix\x1b[0m to resolve them.`);
  }
}

// ---- Main ----
function main() {
  const args = process.argv.slice(2);
  const doFix = args.includes('--fix');
  const dryRun = args.includes('--dry-run');

  console.log('\n\x1b[1m🔍 Assignment Calendar — Config Validator\x1b[0m');
  console.log(`   Files: ${COURSES_PATH}, ${ASSIGNMENTS_PATH}\n`);

  const courseData = loadCourses();
  const data = loadAssignments();
  console.log(`   ${data.assignments.length} assignments, ${data.autoCompleted.length} autoCompleted entries — term: ${courseData.term}`);

  const issues = validate(courseData, data);
  printReport(issues);

  if ((doFix || dryRun) && issues.some(i => i.fixable)) {
    console.log(`\n\x1b[1m${dryRun ? '── Dry Run ──' : '── Applying Fixes ──'}\x1b[0m\n`);
    const fixCount = autoFix(data, issues);
    console.log(`\n  ${fixCount} fix(es) applied.`);
    console.log(`  ${data.assignments.length} assignments remaining, ${data.autoCompleted.length} autoCompleted entries`);

    if (!dryRun) {
      writeAssignments(data);
    } else {
      console.log('\n  \x1b[36m(Dry run — no files were modified)\x1b[0m');
    }

    // Re-validate after fix
    console.log('\n\x1b[1m── Post-fix Validation ──\x1b[0m');
    const postIssues = validate(courseData, data);
    printReport(postIssues);
  }

  // Exit code: 1 if errors remain
  const errorCount = issues.filter(i => i.severity === 'error').length;
  process.exit(errorCount > 0 && !doFix ? 1 : 0);
}

main();
