#!/usr/bin/env node
// ============================================================
// ASSIGNMENT CALENDAR — config.js Validator & Fixer
// ============================================================
// Run:  node validate-config.js           → report only
//       node validate-config.js --fix     → auto-fix and write
//       node validate-config.js --dry-run → show fixes without writing
// ============================================================

const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, 'config.js');
const BACKUP_DIR = path.join(__dirname, 'backups');

// ---- Known-good reference data ----
const VALID_COURSES = ['eecs270', 'eecs370', 'eecs442', 'stats250', 'tc300'];
const VALID_ID_PREFIXES = ['270', '370', '442', 's250', 'tc'];
const VALID_TYPES = [
  'project', 'quiz', 'exam', 'homework', 'prelab',
  'ep', 'lab', 'casestudy', 'lecture', 'assignment'
];

// Words/phrases that indicate announcements or non-assignment items
const JUNK_KEYWORDS = [
  'welcome to',
  'lectures cancelled',
  'office hours',
  'exam conflict form',
  'reiterating expectations',
  'bring resume',
  'on zoom',
  'syllabus agreement form',
  'report outline assignment posted',
  'dr. brehob',
  'sections cancelled',
  'no lecture',
  'class cancelled',
  'reminder:',
  'announcement:',
  'important:',
  'note:',
  'fyi:',
  'update:',
];

// ---- Parse config ----
function loadConfig() {
  const raw = fs.readFileSync(CONFIG_PATH, 'utf8');
  try {
    const fn = new Function(raw + '; return APP_CONFIG;');
    return { config: fn(), raw };
  } catch (e) {
    console.error('\x1b[31m✗ SYNTAX ERROR in config.js:\x1b[0m', e.message);
    process.exit(1);
  }
}

// ---- Validation checks ----
function validate(config) {
  const issues = [];
  const assignments = config.assignments || [];
  const autoCompleted = config.autoCompleted || [];

  // Track IDs for duplicate detection
  const seenIds = new Map(); // id → index
  const seenNames = new Map(); // "course::lowercase-name" → id

  assignments.forEach((a, i) => {
    const loc = `assignments[${i}] (id: "${a.id}")`;

    // 1. Required fields
    if (!a.id) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing id` });
    if (!a.name) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing name` });
    if (!a.course) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing course` });
    if (!a.due) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing due date` });
    if (!a.type) issues.push({ severity: 'error', idx: i, msg: `${loc}: missing type` });

    // 2. Valid course
    if (a.course && !VALID_COURSES.includes(a.course)) {
      issues.push({ severity: 'error', idx: i, msg: `${loc}: unknown course "${a.course}"` });
    }

    // 3. Valid type
    if (a.type && !VALID_TYPES.includes(a.type)) {
      issues.push({ severity: 'warn', idx: i, msg: `${loc}: unusual type "${a.type}"` });
    }

    // 4. ID prefix matches course
    if (a.id && a.course) {
      const prefix = a.id.split('-')[0];
      const expectedPrefixes = {
        eecs270: '270', eecs370: '370', eecs442: '442',
        stats250: 's250', tc300: 'tc'
      };
      if (expectedPrefixes[a.course] && prefix !== expectedPrefixes[a.course]) {
        issues.push({ severity: 'warn', idx: i, msg: `${loc}: id prefix "${prefix}" doesn't match course "${a.course}" (expected "${expectedPrefixes[a.course]}")` });
      }
    }

    // 5. Long auto-generated IDs (scraper artifact)
    if (a.id && a.id.length > 25) {
      issues.push({ severity: 'warn', idx: i, msg: `${loc}: suspiciously long id (${a.id.length} chars) — likely auto-generated by scraper`, fixable: 'long-id' });
    }

    // 6. Duplicate IDs
    if (a.id && seenIds.has(a.id)) {
      issues.push({ severity: 'error', idx: i, msg: `${loc}: DUPLICATE id — also at index ${seenIds.get(a.id)}`, fixable: 'duplicate-id' });
    } else if (a.id) {
      seenIds.set(a.id, i);
    }

    // 7. Duplicate names within same course (fuzzy)
    if (a.name && a.course) {
      const nameKey = `${a.course}::${a.name.toLowerCase().replace(/\s+/g, ' ').trim()}`;
      if (seenNames.has(nameKey)) {
        issues.push({
          severity: 'warn', idx: i,
          msg: `${loc}: possible duplicate name "${a.name}" — similar to "${seenNames.get(nameKey)}"`,
          fixable: 'duplicate-name'
        });
      } else {
        seenNames.set(nameKey, a.id);
      }
    }

    // 8. Junk/announcement detection
    if (a.name) {
      const lower = a.name.toLowerCase();
      for (const kw of JUNK_KEYWORDS) {
        if (lower.includes(kw)) {
          issues.push({
            severity: 'warn', idx: i,
            msg: `${loc}: looks like an announcement/non-assignment — contains "${kw}"`,
            fixable: 'junk'
          });
          break;
        }
      }
    }

    // 9. Date format check (should be YYYY-MM-DD)
    if (a.due && !/^\d{4}-\d{2}-\d{2}$/.test(a.due)) {
      issues.push({ severity: 'error', idx: i, msg: `${loc}: invalid date format "${a.due}" (expected YYYY-MM-DD)` });
    }

    // 10. Date sanity check (should be within W2026 semester: Jan 2026 – Apr 2026)
    if (a.due && /^\d{4}-\d{2}-\d{2}$/.test(a.due)) {
      const d = new Date(a.due + 'T12:00:00');
      if (d < new Date('2026-01-01') || d > new Date('2026-05-15')) {
        issues.push({ severity: 'warn', idx: i, msg: `${loc}: date "${a.due}" is outside the Winter 2026 semester range` });
      }
    }

    // 11. Missing points or hours (not critical but worth noting)
    if (!a.points && a.type !== 'lecture') {
      issues.push({ severity: 'info', idx: i, msg: `${loc}: no points value` });
    }
    if (a.hours === undefined && a.type !== 'lecture') {
      issues.push({ severity: 'info', idx: i, msg: `${loc}: no hours estimate` });
    }
  });

  // 12. Stale autoCompleted references
  const allIds = new Set(assignments.map(a => a.id));
  autoCompleted.forEach(id => {
    if (!allIds.has(id)) {
      issues.push({ severity: 'warn', idx: -1, msg: `autoCompleted: stale id "${id}" not found in assignments`, fixable: 'stale-autocomplete' });
    }
  });

  // 13. Duplicate autoCompleted entries
  const seenAC = new Set();
  autoCompleted.forEach((id, i) => {
    if (seenAC.has(id)) {
      issues.push({ severity: 'warn', idx: -1, msg: `autoCompleted[${i}]: duplicate entry "${id}"`, fixable: 'duplicate-autocomplete' });
    }
    seenAC.add(id);
  });

  return issues;
}

// ---- Auto-fix ----
function autoFix(config, issues) {
  const toRemoveIdxs = new Set();
  const staleACIds = new Set();
  let fixed = 0;

  for (const issue of issues) {
    if (issue.fixable === 'duplicate-id' && issue.idx >= 0) {
      toRemoveIdxs.add(issue.idx);
      fixed++;
    }
    if (issue.fixable === 'junk' && issue.idx >= 0) {
      toRemoveIdxs.add(issue.idx);
      fixed++;
    }
    if (issue.fixable === 'stale-autocomplete') {
      const match = issue.msg.match(/stale id "(.+?)"/);
      if (match) staleACIds.add(match[1]);
      fixed++;
    }
  }

  // Remove flagged assignments (in reverse order to preserve indices)
  const removedIds = new Set();
  const sortedIdxs = [...toRemoveIdxs].sort((a, b) => b - a);
  for (const idx of sortedIdxs) {
    const removed = config.assignments[idx];
    removedIds.add(removed.id);
    console.log(`  \x1b[33m→ Removing:\x1b[0m ${removed.id} ("${removed.name}")`);
    config.assignments.splice(idx, 1);
  }

  // Clean autoCompleted: remove stale refs and deduplicate
  // Only remove an ID if it's truly gone (not just a duplicate that was removed while the original remains)
  const remainingIds = new Set(config.assignments.map(a => a.id));
  const beforeAC = config.autoCompleted.length;
  config.autoCompleted = [...new Set(
    config.autoCompleted.filter(id => !staleACIds.has(id) && remainingIds.has(id))
  )];
  const removedAC = beforeAC - config.autoCompleted.length;
  if (removedAC > 0) {
    console.log(`  \x1b[33m→ Removed ${removedAC} stale/duplicate autoCompleted entries\x1b[0m`);
  }

  return fixed;
}

// ---- Write config back ----
function writeConfig(config, raw) {
  // Create backup first
  if (!fs.existsSync(BACKUP_DIR)) fs.mkdirSync(BACKUP_DIR, { recursive: true });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const backupPath = path.join(BACKUP_DIR, `config-${timestamp}.js`);
  fs.writeFileSync(backupPath, raw);
  console.log(`\n  \x1b[36mBackup saved:\x1b[0m ${backupPath}`);

  // Rebuild config.js by replacing the assignments array and autoCompleted array in the raw text
  let output = raw;

  // Replace assignments array
  const assignmentsStr = config.assignments.map(a => {
    const fields = [];
    fields.push(`      id: ${JSON.stringify(a.id)}`);
    fields.push(`      name: ${JSON.stringify(a.name)}`);
    fields.push(`      course: ${JSON.stringify(a.course)}`);
    fields.push(`      due: ${JSON.stringify(a.due)}`);
    fields.push(`      time: ${a.time ? JSON.stringify(a.time) : 'null'}`);
    fields.push(`      type: ${JSON.stringify(a.type)}`);
    fields.push(`      points: ${JSON.stringify(a.points)}`);
    fields.push(`      hours: ${a.hours}`);
    if (a.specUrl) fields.push(`      specUrl: ${JSON.stringify(a.specUrl)}`);
    return `    {\n${fields.join(',\n')}\n    }`;
  }).join(',\n');

  // Find and replace the assignments array
  const assignStart = output.indexOf('assignments: [');
  if (assignStart === -1) {
    console.error('\x1b[31m✗ Could not locate assignments array in config.js\x1b[0m');
    process.exit(1);
  }
  // Find the matching closing bracket
  let depth = 0;
  let assignEnd = -1;
  for (let i = assignStart + 'assignments: '.length; i < output.length; i++) {
    if (output[i] === '[') depth++;
    if (output[i] === ']') {
      depth--;
      if (depth === 0) { assignEnd = i + 1; break; }
    }
  }
  output = output.slice(0, assignStart) + `assignments: [\n${assignmentsStr}\n  ]` + output.slice(assignEnd);

  // Replace autoCompleted array
  const acStr = config.autoCompleted.map(id => `    ${JSON.stringify(id)}`).join(',\n');
  const acStart = output.indexOf('autoCompleted: [');
  if (acStart !== -1) {
    let depth2 = 0;
    let acEnd = -1;
    for (let i = acStart + 'autoCompleted: '.length; i < output.length; i++) {
      if (output[i] === '[') depth2++;
      if (output[i] === ']') {
        depth2--;
        if (depth2 === 0) { acEnd = i + 1; break; }
      }
    }
    output = output.slice(0, acStart) + `autoCompleted: [\n${acStr}\n  ]` + output.slice(acEnd);
  }

  // Verify syntax before writing
  try {
    new Function(output);
  } catch (e) {
    console.error('\x1b[31m✗ Generated config has syntax errors — aborting write!\x1b[0m');
    console.error('  ', e.message);
    process.exit(1);
  }

  fs.writeFileSync(CONFIG_PATH, output);
  console.log(`  \x1b[32m✓ config.js updated successfully\x1b[0m`);
}

// ---- Reporting ----
function printReport(issues) {
  const errors = issues.filter(i => i.severity === 'error');
  const warns = issues.filter(i => i.severity === 'warn');
  const infos = issues.filter(i => i.severity === 'info');

  if (issues.length === 0) {
    console.log('\n\x1b[32m✓ config.js is clean — no issues found!\x1b[0m\n');
    return;
  }

  console.log(`\n\x1b[1m── Validation Report ──\x1b[0m\n`);

  if (errors.length > 0) {
    console.log(`\x1b[31m✗ ${errors.length} error(s):\x1b[0m`);
    errors.forEach(i => console.log(`  \x1b[31m•\x1b[0m ${i.msg}`));
    console.log();
  }
  if (warns.length > 0) {
    console.log(`\x1b[33m⚠ ${warns.length} warning(s):\x1b[0m`);
    warns.forEach(i => console.log(`  \x1b[33m•\x1b[0m ${i.msg}`));
    console.log();
  }
  if (infos.length > 0) {
    console.log(`\x1b[36mℹ ${infos.length} info:\x1b[0m`);
    infos.forEach(i => console.log(`  \x1b[36m•\x1b[0m ${i.msg}`));
    console.log();
  }

  const fixable = issues.filter(i => i.fixable).length;
  if (fixable > 0) {
    console.log(`  ${fixable} issue(s) are auto-fixable. Run with \x1b[1m--fix\x1b[0m to resolve them.`);
  }
}

// ---- Main ----
function main() {
  const args = process.argv.slice(2);
  const doFix = args.includes('--fix');
  const dryRun = args.includes('--dry-run');

  console.log('\n\x1b[1m🔍 Assignment Calendar — Config Validator\x1b[0m');
  console.log(`   File: ${CONFIG_PATH}\n`);

  const { config, raw } = loadConfig();
  console.log(`   ${config.assignments.length} assignments, ${config.autoCompleted.length} autoCompleted entries`);

  const issues = validate(config);
  printReport(issues);

  if ((doFix || dryRun) && issues.some(i => i.fixable)) {
    console.log(`\n\x1b[1m${dryRun ? '── Dry Run ──' : '── Applying Fixes ──'}\x1b[0m\n`);
    const fixCount = autoFix(config, issues);
    console.log(`\n  ${fixCount} fix(es) applied.`);
    console.log(`  ${config.assignments.length} assignments remaining, ${config.autoCompleted.length} autoCompleted entries`);

    if (!dryRun) {
      writeConfig(config, raw);
    } else {
      console.log('\n  \x1b[36m(Dry run — no files were modified)\x1b[0m');
    }

    // Re-validate after fix
    console.log('\n\x1b[1m── Post-fix Validation ──\x1b[0m');
    const postIssues = validate(config);
    printReport(postIssues);
  }

  // Exit code: 1 if errors remain
  const errorCount = issues.filter(i => i.severity === 'error').length;
  process.exit(errorCount > 0 && !doFix ? 1 : 0);
}

main();
